name: Notificación a ntfy.sh

on:
  push:
    branches:
      - main

jobs:
  enviar-alerta:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar notificación
        run: |
          curl -d "🚀 Código nuevo en el repositorio" ntfy.sh/devops-itla
